### ISSUE TITLE
Issueのテンプレートを作りたい

### ISSUE THREAD

**Issue by telumo** [dangobro/monii#1]
Issueのテンプレートがないため、作りたい。

**Comment by skm-isy** [comment]
## 2020/04/21  2:43【メモ】
[リポジトリ用 Issue テンプレートの設定 \- GitHub ヘルプ](https://help.github.com/ja/github/building-a-strong-community/configuring-issue-templates-for-your-repository)を参考にする。

**Comment by skm-isy** [comment]
## 2020/04/21  2:56【メモ】

[create issue templates](https://github.com/dangobro/monii/commit/8bd64710320f702bb55092de399e1039fee02497)
[Update issue templates](https://github.com/dangobro/monii/commit/2b83c233bc8348c9741b02ad7fda3d7b07427053)
にてテンプレートファイルをコミットした。

[issueページ](https://github.com/dangobro/monii/issues)にて、
「New Issue」ボタンを押すと、
![image](https://user-images.githubusercontent.com/53833076/79783695-04ec4d80-837c-11ea-8501-55f78e1d8a68.png)

[New issueページ](https://github.com/dangobro/monii/issues/new/choose)にて、
"incident" あるいは "issue"を選択するようになるので、
![image](https://user-images.githubusercontent.com/53833076/79783762-1c2b3b00-837c-11ea-8f33-31f46d9951d7.png)

通常の開発進行には”Issue”を用いる。
もしエラーが発覚し、サービス品質を著しく低下させるような事象が起こった場合に、”incident”を用いる。
Service提供前には使わない想定だが、想定していないコスト上昇などもここに含めることにする。

**Comment by skm-isy** [comment]
@telumo 
https://github.com/dangobro/monii/issues/1#issuecomment-616719234
にて2種類のissueの棲み分けについてコメントしています。
御確認ください。
WIKIにも記載しておきます。

**Comment by skm-isy** [comment]
- [ ] WIKIにissueの棲み分けについて記載してください @skm-isy 

----

上記タスクが完了次第、クローズします。

**Comment by skm-isy** [comment]
## 2020/04/21  3:25【メモ】
[Issue作成手順 · dangobro/monii Wiki](https://github.com/dangobro/monii/wiki/Issue%E4%BD%9C%E6%88%90%E6%89%8B%E9%A0%86)にてWIKI作成したので、クローズします。

**Comment by skm-isy** [comment]
テストテスト
