### ISSUE TITLE
Community profileを充実させる

### ISSUE THREAD

**Issue by telumo** [dangobro/monii#9]
# 背景/課題
- Open Sourceの流儀に則ってCommunity Profileを充実させたい。（後学のため）

# やりたいこと

- [Community](https://github.com/dangobro/monii/community)を全てチェック状態にする。

# 対応

- [x]  Description 

- [x]  README

- [ ] Code of conduct

- [x] Contributing

- [ ] License

- [x] Issue templates

- [x] Pull request template

# 関連

- [LICENSE確認したい · Issue \#5 · dangobro/monii](https://github.com/dangobro/monii/issues/5)

**Comment by telumo** [comment]
未完了のタスクを別Issueに切り分けたためクローズする

- [Code Of Conductを作成する · Issue \#10 · dangobro/monii](https://github.com/dangobro/monii/issues/10)

- [LICENSE確認したい · Issue \#5 · dangobro/monii](https://github.com/dangobro/monii/issues/5)

**Comment by skm-isy** [comment]
@telumo 
`Code of conduct` は別切り出した方が良い気がします。
[Code of Conduct（行動規範） \| Ubuntu Japanese Team](http://www.ubuntulinux.jp/community/conduct)や[デロイト トーマツ グループ Code of Conduct｜コーポレート：グループ案内｜デロイト トーマツ グループ｜Deloitte](https://www2.deloitte.com/jp/ja/pages/about-deloitte/articles/about-deloitte-japan/coc.html)のようにServiceの行動規範はみんなで合意取りながらの方が良いと思うからです。
